keycloak:
  auth-server-url: http://localhost:8080/
  realm: SpringBootKeycloack
  ssl-required: external
  use-resource-role-mappings: true
server:
  port: 8081
  servlet:
    context-path: /api

logging:
  level:
    org.springframework.security: DEBUG
spring:
  application:
    name: MusicTranslatorBackEnd
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:./test.db
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-ui
  jpa:
    hibernate:
      #ddl-auto: create-drop
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/SpringBootKeycloack
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  jwt:
    auth:
      converter:
        resource-id: SpringBootKeycloack
        principal-attribute: preferred_username
